[general]
live_config_reload = true
import = [
    "./alacritty-theme/themes/catppuccin_macchiato.toml"
]

[window]
startup_mode = "Maximized"

[font]
normal = { family = "HackGen Console NF", style = "Regular" }

[selection]
save_to_clipboard = true
